agripo_website/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.contrib import auth

from core import urls as core_urls
from django.conf import settings
from django.contrib.auth.views import logout
from django.contrib.flatpages import views as flatpages_views
from registration.backends.hmac.views import RegistrationView
from registration.forms import RegistrationFormUniqueEmail


urlpatterns = [
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=RegistrationFormUniqueEmail),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^accounts/login/$', auth.views.login, name='account_login'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include('admin_helper.urls')),
    url(r'^webdoc/', include('webdoc.urls', namespace="webdoc")),
    url(r'', include(core_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<url>.*/)$', flatpages_views.flatpage),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns(
        '',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT}))

core/urls.py
from core.authentication import is_staging_server, is_development_server
from django.conf.urls import url, patterns
from django.contrib.auth.views import logout
from django.views.generic import RedirectView, TemplateView, ListView
from django.views.decorators.cache import never_cache

from core import views
from core.models.partners import Partner


urlpatterns = [
    url(r'^$', views.index_view, name="home_page"),
    url(r'^logout$', logout, {'next_page': '/'}, name='logout'),
    url(r'^using_cookies_accepted/$', views.using_cookies_accepted, name="using_cookies_accepted"),
    url(r'^news/$', views.NewsListPage.as_view(), name="news_page"),
    url(r'^care/$', views.CareListPage.as_view(), name="care_page"),
    url(r'^partners/$', ListView.as_view(
        model=Partner, template_name='core/partners_page.html', context_object_name="partners"), name="partners_page"),
    url(r'^shop/(?P<pk>[0-9]+)/$', views.ShopPage.as_view(), name="shop_page"),
    url(r'^shop/checkout$', never_cache(views.Checkout.as_view()), name="checkout"),
    url(r'^shop/get_cart$', never_cache(views.get_cart), name="get_cart"),
    url(r'^shop/update_stock$', never_cache(views.UpdateStock.as_view()), name="update_stock"),
    url(r'^admin/core/delivery/(?P<id>[0-9]+)/details/$', views.delivery_details, name="delivery_details"),
    url(r'^shop/command_successfull', TemplateView.as_view(
        template_name="core/command_successfull.html"), name="command_successfull"),
    url(r'^shop/set_product_quantity/(?P<product>[0-9]+)/(?P<quantity>[0-9]+)/',
        never_cache(views.set_product_quantity), name="set_product_quantity"),
    url(r'^requires_js$', views.RequiresJs.as_view(), name="requires_js"),
    url(r'^menu_(?P<page>[a-z_]+)/$', views.SubMenusPage.as_view(), name="menu_page"),
    url(r'^news/(?P<pk>[0-9]+)/$', views.NewsPage.as_view(), name="one_news_page"),
    url(r'^care/(?P<pk>[0-9]+)/$', views.CarePage.as_view(), name="one_care_page"),
    url(r'^reservation/$', views.ReservationView.as_view(), name="reservation_page"),
    url(r'^reservation_ok/$', TemplateView.as_view(
        template_name="core/reservation_ok.html"), name="reservation_ok_page"),
    url(r'^backup/$', views.get_backup, name="backup"),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/shared/favicon.ico', permanent=True)),
]

if is_staging_server() or is_development_server():
    urlpatterns += patterns(
        '',
        url(r'^core/auto_login/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+)$',
            views.auto_connect, {'manager': False}, name='auto_connect'),
        url(r'^core/auto_manager_login/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+)$',
            views.auto_connect, {'manager': True}, name='auto_manager_connect'),
        url(r'^core/populatedb/(?P<news_count>[0-9]+)/(?P<products_count>[0-9]+)/(?P<categories_count>[0-9]+)/$',
            views.populate_db, name='populate_db'),
    )

webdoc/urls.py
from django.conf.urls import url
from webdoc.views import get_focus
from django.views.generic.base import TemplateView


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="webdoc/index.html"), name="home_page"),
    url(r'^webdoc$', TemplateView.as_view(template_name="webdoc/webdoc.html"), name='webdoc'),
    url(r'^project$', TemplateView.as_view(template_name="webdoc/project.html"), name='project'),
    url(r'^support$', TemplateView.as_view(template_name="webdoc/support.html"), name='support'),
    url(r'^partners$', TemplateView.as_view(template_name="webdoc/partners.html"), name='partners'),
    url(r'^credits$', TemplateView.as_view(template_name="webdoc/credits.html"), name='credits'),
    url(r'^focus/theme(?P<theme>[0-9])_focus(?P<focus>[0-9])/$', get_focus, name='focus'),
]

core/models/partners.py
from ckeditor.fields import RichTextField
from django.conf import settings
from django.db import models


class Partner(models.Model):
    on_change_delete_cache = True
    name = models.CharField(
        max_length=128, unique=True, verbose_name="Nom du partenaire", help_text="Nom du partenaire",
        default=None)
    description = RichTextField(
        config_name='awesome_ckeditor', verbose_name="Description du partenaire",
        help_text="Contenu de la page d'accueil", default=None
    )
    website = models.URLField(verbose_name="Site internet du partenaire", default=None)
    logo = models.ImageField(
        upload_to='partners', blank=False, default=None, verbose_name="Logo (330x220 px)",
        help_text="Envoyez le logo du partenaire ici.<br />"
                  "<strong>Il doit faire 330x220px</strong> pour ne pas être déformé. "
    )

    def __str__(self):
        return self.name

    def logo_tag(self):
        return u'<img src="{}" style="width:150px;height:150px;"/>'.format(settings.MEDIA_URL + str(self.logo))

    logo_tag.short_description = 'Logo'
    logo_tag.allow_tags = True

    class Meta:
        verbose_name = "Partenaire"

webdoc/views.py
from django.shortcuts import render_to_response


def get_focus(context, theme=None, focus=None):
    template_name = "webdoc/focus/theme{}_focus{}.html".format(theme, focus)
    return render_to_response(template_name=template_name)

webdoc/templates/webdoc/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>{% block head_title %}Agripo{% endblock %}</title>
    <!-- BOOTSTRAP CORE STYLE CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet"/>
    <!-- FONTAWESOME STYLE CSS -->
    <link href="/static/css/font-awesome.min.css" rel="stylesheet"/>
    <!-- CUSTOM STYLE CSS from the template -->
    <link href="/static/css/style.css" rel="stylesheet"/>
    <!-- CUSTOM STYLE CSS -->
    <link href="/static/css/base.css" rel="stylesheet"/>
    <link type="text/css" rel="stylesheet" href="/static/css/webdoc/base.css"></link>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!--<link href="/static/css/jquery-ui/humanity/jquery-ui.css" rel='stylesheet' type='text/css' />-->
    <!-- GOOGLE FONT -->
    <!--    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'/>-->

    <script src="/static/js/base.js"></script>
</head>
<body id="id_webdoc_pages">
{% block body %}
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container" id="id_top_container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="/">
                    <img src="/static/img/logo_bg_transp.png" style="height:50px;margin-top:-14px;"/>
                </a>
            </div>


            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <ul class="nav navbar-nav navbar-right" id="text_menus">
                    <li class="dropdown">
                        <a href="{% url "home_page" %}">
                            Retour au site d'Agripo
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    {% if not cookies_notification_shown %}
        {% include "core/boxes/cookies.html" %}
    {% endif %}


    <div id="webdoc_main_container">
        <div id="{% block page_type %}pages{% endblock %}">
            {% block main_content %}
                Block main_content should be used is a subtemplate
            {% endblock %}
            <div id="footer">
                <div id="menu">
                    <menu>
                        <a href="{% url "webdoc:webdoc" %}">
                            Webdoc
                        </a>
                        <a href="{% url "webdoc:project" %}">
                            Projet
                        </a>
                        <a href="{% url "webdoc:support" %}">
                            Soutenir
                        </a>
                        <a href="{% url "webdoc:partners" %}">
                            Partenaires
                        </a>
                        <a href="{% url "webdoc:credits" %}">
                            Crédits
                        </a>
                    </menu>
                </div>
                <div id="social" class="social_panel">
                    <a href="https://plus.google.com/u/0/102083009182719388517/posts" target="_blank" class="brown round_logo" style="">
                        <img src="/static/img/webdoc/logo_googleplus.png" class="social_media_logo"/>
                    </a>
                    <a href="https://twitter.com/COOPAGRIPO" target="_blank" class="brown round_logo" style="">
                        <img src="/static/img/webdoc/logo_twitter.png" class="social_media_logo"/>
                    </a>
                    <a href="https://fr-fr.facebook.com/AgriculteursProfessionnelsDuCameroun" target="_blank" class="brown round_logo" style="">
                        <img src="/static/img/webdoc/logo_facebook.png" class="social_media_logo"/>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <nav id="main_nav">
    </nav>

    <!--/.FOOTER END-->
    <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
    <!-- CORE JQUERY  -->
    <script src="/static/js/jquery-1.10.2.js" type="text/javascript"></script>
    <!--<script src="/static/js/jquery-ui.js" type="text/javascript"></script>-->
    <!-- BOOTSTRAP SCRIPTS  -->
    <script src="/static/js/bootstrap.js"></script>
    <!-- Vars & dom is loaded  -->
    <script>
        $(function($){
            URL_COOKIES_ACCEPTED = '{% url 'using_cookies_accepted' %}';
            dom_is_loaded($);
        });
    </script>
{% endblock %}
{% block extra_body %}
{% endblock extra_body %}
</body>
</html>

webdoc/templates/webdoc/credits.html
{% extends 'webdoc/base.html' %}

{% block main_content %}
<div id="page_credits">
    <div id="content">
        <h3>Remerciements</h3>
        <p>
            Nous tenons à remercier Laura Guien et Brice Parent, mobilisés via
            www.onlinevolunteering.org, pour l’aide apportée à la production de ce
            webdocumentaire.
        </p>

        <h3>Ecriture et réalisation</h3>
        <p>Ecrit par Laura Guien, Adeline Flore Ngo-Samnick et Lionelle Ngo-Samnick.</p>
        <p>Réalisation et intégration par Brice Parent</p>

        <h3>Crédits photos</h3>


        <a href="/webdoc.php">
            <input type="button" class="button" value="Retourner au webdoc" style="position:absolute;left:300px;top:400px;"/>
        </a>
    </div>
</div>
{% endblock %}

webdoc/templates/webdoc/index.html
{% extends 'webdoc/base.html' %}

{% block main_content %}
<div id="page_index">
    <div id="content">
        <style>
            #content img{
                position:absolute;
                width:320px;
                left:120px;
                top:35px;
            }
            #content p{
                color:white;
                text-align: left;
                position:absolute;
                top:160px;
                left:143px;
                width:300px;
                font-size: 12px;
            }
            #content a input{
                position:absolute;
                left:320px;
                top:280px;
            }
            @media
            screen and (min-width: 830px) and (max-width:1280px),
            screen and (min-width: 830px) and (max-height:729px){
                #content img{
                    width:320px;
                    left:180px;
                    top:100px;
                }
                #content p{
                    top:260px;
                    left:203px;
                    width:550px;
                    font-size: 14px;
                }
                #content a input{
                    left:480px;
                    top:380px;
                }

            }
            @media screen and (min-width: 1281px) and (min-height:730px) {
                #content img{
                    width:320px;
                    left:360px;
                    top:150px;
                }
                #content p{
                    top:360px;
                    left:323px;
                    width:550px;
                    font-size: 16px;
                }
                #content a input{
                    left:630px;
                    top:540px;
                }

            }
        </style>
        <img src="/static/img/webdoc/logo_webdoc.png"/>
        <p class="text_shadow">
            Le Cameroun est l'un des pays d'Afrique souffrant le plus de la déforestation.<br />
            À Tayap, dans le centre du pays, un program&shy;me original de dévelop&shy;pement
            éco&shy;touristique et agro&shy;écologique lutte au quoti&shy;dien pour faire reculer
            ce fléau et améliorer les condi&shy;tions de vie en milieu rural.
        </p>
        <a href="{% url "webdoc:webdoc" %}">
            <input type="button" class="button" value="Accéder au webdoc"/>
        </a>
    </div>
</div>
{% endblock %}

webdoc/templates/webdoc/partners.html
{% extends 'webdoc/base.html' %}

{% block main_content %}
<div id="page_project">
    <div id="content">
        <div id="content" style="overflow-y:auto;">
            <div>
                <a href="{% url "webdoc:home_page" %}">
                    <img src="/static/img/webdoc/logo_webdoc.png" style="width:320px;left:0px;top:10px;"/>
                </a>
                <h1>Nos partenaires</h1>
                <p>
                    Le programme « Vergers écologiques de Tayap » est soutenu par le SGP/GEF du PNUD, ISF
                    Cameroun, SEED Initiatives et WWF's Russell E. Train Education for Nature Program.
                </p>

                <h3>Small Grant Program, GEF du Programme des Nations Unies pour le développement</h3>
                <p>Créé en 1992, l'année du Sommet de la Terre de Rio, le Programme de microfinancements du GEF (Small Grant Program ou SGP)  incarne l'essence même du développement durable par «penser globalement agir localement". En apportant un soutien financier et technique à des projets de conservation et de restauration de l'environnement tout en améliorant le bien-être et les moyens de subsistance des gens, le SGP démontre que l'action communautaire peut maintenir l'équilibre délicat entre les besoins humains et les impératifs environnementaux.</p>
                <a href="https://sgp.undp.org/index.php">https://sgp.undp.org/index.php</a>

                <h3>ISF Cameroun </h3>
                <p>Conscients de leur responsabilité dans le développement du Cameroun, ISF a été créé le 14 Octobre 2003 à l’initiative de quelques ingénieurs issus de différentes écoles d’ingénierie au Cameroun, pour aider les communautés défavorisées dans leur lutte contre la pauvreté à travers des études techniques adaptées aux besoins exprimés et si possible la mise en œuvre de projets d’ingénierie économiquement fiables, sociologiquement viables et écologiquement acceptables.</p>
                <a href="http://www.isf-cameroun.org/fr">http://www.isf-cameroun.org/fr</a>

                <h3>SEED Initiatives</h3>
                <p>L'entrepreneuriat social et environnemental, aussi connu comme l'éco-entrepreneuriat, est essentiel pour le développement durable et la réduction de la pauvreté. Pour accélérer sa croissance, le PNUE, le PNUD et l'UICN ont fondé l'initiative SEED lors du Sommet mondial 2002 sur le développement durable à Johannesburg afin d' aider les petites entreprises  dans les pays en développement à renforcer leurs avantages sociaux, environnementaux et économiques. Les SEED Awards et Support lancés en 2005, représentent un élément central du programme. Les Vergers écologiques de Tayap ont été lauréat des Seed Awards en 2011. </p>
                <a href="http://www.seed.uno/awards/all/2011/540-tayap-eco-orchards.html">http://www.seed.uno/awards/all/2011/540-tayap-eco-orchards.html</a>

                <h3>WWF's Russell E. Train Education for Nature Program</h3>
                <p>Depuis 1994, le programme Russell E. Train Education for Nature (EFN) donne de l'aide financière aux dirigeants de la conservation en Afrique, en Asie et en Amérique latine, pour acquérir les compétences et connaissances dont ils ont besoin et relever les défis de conservation dans leurs pays d'origine. L'EFN soutient les conservateurs de la nature à poursuivre leurs études supérieures, à assister à des formations professionnelles, et à organiser les ateliers dans les communautés locales. </p>
                <a href="www.worldwildlife.org/efn">www.worldwildlife.org/efn</a>


                <div style="text-align:center;margin:10px;">
                    <a href="{% url "webdoc:webdoc" %}">
                        <input type="button" class="button" value="Retourner au webdoc"/>
                    </a>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

webdoc/templates/webdoc/project.html
{% extends 'webdoc/base.html' %}

{% block main_content %}
<div id="page_project">
    <div id="content">
        <style>
            #page_project #content li{
                width:540px;
                text-align: justify;
            }
            #page_project #content li li{
                width:500px;
            }
        </style>
        <div id="content" style="overflow-y:auto;">
            <a href="{% url "webdoc:home_page" %}">
                <img src="/static/img/webdoc/logo_webdoc.png" style="width:320px;left:0px;top:10px;"/>
            </a>
            <h1>Le projet</h1>

            <img src="/static/img/webdoc/projet_1.jpg" style="width:300px;padding:10px;float:right"/>
            <p>
                Les Vergers Ecologiques de Tayap » (VET)  est un  programme de développement rural
                innovant qui s’appuie sur l’agroécologie, l’écotourisme et la finance verte pour
                préserver la biodiversité et les terres du village de Tayap . Ce programme pilote
                ambitieux et chargé de valeurs est le fruit de la mobilisation d'une communauté
                solidaire et engagée et s'inscrit dans une démarche globale et durable qui intègre
                les besoins de la population aux enjeux sociaux, économiques et environnementaux.
            </p>

            <p>
                Le projet s’inscrit dans la voie du développement durable et de l’économie verte en
                particulier. Il est l’illustration pratique du « Penser global, agir local » selon
                la formule de René DUBOS.
            </p>

            <p>
                Les objectifs des vergers écologiques de Tayap sont multiples :
            </p>
            <ul>
                <li>Préserver les ressources naturelles et la biodiversité </li>
                <li>Lutter contre le changement climatique </li>
                <li>Assurer un revenu durable et une protection sociale à la communauté pour sortir de la précarité </li>
                <li>Diversifier l’emploi en milieu rural </li>
                <li>Intégrer les femmes dans les dynamiques de développement </li>
                <li>Tester une expérience locale de financement innovant </li>
            </ul>

            <p>3 volets principaux d’actions sont développés : l’agroforesterie, l’écotourisme et la microfinance solidaire. </p>

            <img src="/static/img/webdoc/projet_2.jpg" style="float:right;width:400px;padding:10px;"/>
            <ul>
                <li>
                    <strong>L’agroforesterie : </strong>
                    <ul>
                        <li>
                            Changement du mode d’exploitation des terres pour lutter contre la
                            déforestation : 60 hectares de terres agricoles sont déjà mis en valeur
                            pour promouvoir l’agroforesterie de rente (arbres fruitiers et cultures
                            vivrières exploités en agriculture biologique).
                        </li>
                        <li>La vente des produits agricoles et des produits forestiers non ligneux constitue une des ressources de la communauté.
                    </ul>
                </li>
                <li>
                    <strong>L’écotourisme : </strong>Développement d’une offre éco touristique avec des chambres d’hôtes
                    et des écogîtes en construction, mais également des activités de découverte des
                    richesses culturelles et écologiques du village.
                </li>
                <li>
                    <strong>La micro finance solidaire : </strong>
                    <ul>
                        <li>Mise en place d’un fond rotatif de développement sous forme d’une caisse communautaire d’épargne et de crédit. </li>
                        <li>Impulsion d’une nouvelle forme de solidarité par le prêt pour financer et accompagner des initiatives entrepreneuriales portées par des femmes. </li>
                    </ul>
                </li>
            </ul>

            <p>
                D’autres actions d’accompagnement sont également mises en place, comme la protection des
                espèces menacées, dont le Picatharte chauve (aménagement d’un parc communautaire autour de
                la zone de présence de l’oiseau pour préserver son habitat), la sensibilisation au développement
                durable (sensibilisation des agriculteurs à la conservation des terres, sensibilisation des enfants
                par l’organisation de classes vertes), les formations à l’agriculture biologique, à l’écotourisme, à
                la gestion d’une coopérative rurale, ou encore la promotion des femmes (implication des femmes
                aux différents postes du programme : gestion de la coopérative, du programme, du fond rotatif... ;
                soutien à leurs activités dans le cadre du programme).
            </p>

            <div style="text-align:center;margin:10px;">
                <a href="{% url "webdoc:webdoc" %}">
                    <input type="button" class="button" value="Retourner au webdoc"/>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

webdoc/templates/webdoc/support.html
{% extends 'webdoc/base.html' %}

{% block main_content %}
<div id="page_support">
    <div id="content">
        <div id="content">
            <a href="{% url "webdoc:home_page" %}">
                <img src="/static/img/webdoc/logo_webdoc.png" style="width:320px;left:0px;top:10px;"/>
            </a>
            <h1>Soutenir l'initiative</h1>
            <p>Les Vergers écologiques de Tayap ont besoin de soutien. </p>
            <p>Vous pouvez soutenir l'initiative en faisant un don ici : </p>
            <a style="text-decoration: underline;" href="http://www.agripo.net/fr/content/faire-un-don">www.agripo.net/fr/content/faire-un-don</a>

            <a href="{% url "webdoc:webdoc" %}">
                <input type="button" class="button" value="Retourner au webdoc" style="position:absolute;left:300px;top:400px;"/>
            </a>
        </div>
    </div>
</div>
{% endblock %}